name: Asana

on:
  merge_group:
    types:
      - checks_requested

  pull_request:
    types:
      - assigned
      - unassigned
      - review_requested
      - review_request_removed
      - opened
      - synchronize
      - closed
      - edited
      - converted_to_draft
      - ready_for_review

  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Asana:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: mobsuccess-devops/github-actions-asana@master
        with:
          asana-pat: ${{ secrets.ASANA_PAT }}
          github-token: ${{ github.token }}
          action: "synchronize"
          amplify-uri: ${{ secrets.AWS_AMPLIFY_URI }}
          storybook-amplify-uri: ${{ secrets.AWS_STORYBOOK_AMPLIFY_URI }}
