name: Asana

on:
  pull_request:
    types:
      - assigned
      - unassigned
      - review_requested
      - review_request_removed
      - opened
      - synchronize
      - closed
      - edited

  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

jobs:
  Asana:
    runs-on: ubuntu-latest
    steps:
      - uses: mobsuccess-devops/github-actions-asana@master
        with:
          asana-pat: ${{ secrets.ASANA_PAT }}
          github-token: ${{ github.token }}
          trigger-phrase: "(ticket|asana)"
          action: "synchronize"
          comment-id: "#pr:${{env.PR_NUMBER}}"
